config/routes.rb
Rails.application.routes.draw do
  root "books#index"
  resources :book_loans
  resources :people, as: "people"
  resources :books, as: "books"
  get 'logout', to: "login#logout"
  get 'login', to: "login#login_form"
  post 'login', to: "login#login"
  post 'loan_book', to: "book_loans#loan_book"
  patch 'return_book', to: "book_loans#return_book"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_loans, -> { where(returned: false) }
end

app/models/book_loan.rb
class BookLoan < ApplicationRecord
  after_initialize :ensure_values_are_present
  validates :due, presence: true
  validates :returned, inclusion: { in: [true, false] }
  validates :book_id, presence: true
  validates :person_id, presence: true
  
  belongs_to :person
  belongs_to :book

  def ensure_values_are_present
    if self.new_record?
      if !!self.returned != self.returned
        self.returned = false
      end
      self.due ||= Time.now + 2.months
    end
  end
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_loans_controller.rb
class BookLoansController < ApplicationController
  before_action :set_book_loan, only: [:show, :edit, :update, :destroy]

  def loan_book
    person_id = session[:current_user_id]
    book_id = params[:book][:book_id]
    if BookLoan.new(book_id: book_id, person_id: person_id).save
      book = Book.find_by(id: book_id)
      redirect_to :books, flash: { notice: "Enjoy #{book.name}!" }
    else
      redirect_to :books, flash: { error: "Error loaning book!" }
    end
  end

  def return_book
    book_loan_id = params[:book_loan][:book_loan_id]
    puts "returning book", book_loan_id
    loan = BookLoan.find_by(id: book_loan_id)
    if loan && loan.update(returned: true)
      book = Book.find_by(id: loan.book_id)
      redirect_to :books, flash: { notice: "Hope you enjoyed #{book.name}!" }
    else
      redirect_to :books, flash: { error: "Error returning book!" }
    end
  end

  # GET /book_loans
  # GET /book_loans.json
  def index
    @book_loans = BookLoan.all
  end

  # GET /book_loans/1
  # GET /book_loans/1.json
  def show
  end

  # GET /book_loans/new
  def new
    @book_loan = BookLoan.new
  end

  # GET /book_loans/1/edit
  def edit
  end

  # POST /book_loans
  # POST /book_loans.json
  def create
    @book_loan = BookLoan.new(book_loan_params)

    respond_to do |format|
      if @book_loan.save
        format.html { redirect_to @book_loan, notice: "Book loan was successfully created." }
        format.json { render :show, status: :created, location: @book_loan }
      else
        format.html { render :new }
        format.json { render json: @book_loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_loans/1
  # PATCH/PUT /book_loans/1.json
  def update
    respond_to do |format|
      if @book_loan.update(book_loan_params)
        format.html { redirect_to @book_loan, notice: "Book loan was successfully updated." }
        format.json { render :show, status: :ok, location: @book_loan }
      else
        format.html { render :edit }
        format.json { render json: @book_loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_loans/1
  # DELETE /book_loans/1.json
  def destroy
    @book_loan.destroy
    respond_to do |format|
      format.html { redirect_to book_loans_url, notice: "Book loan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book_loan
    @book_loan = BookLoan.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_loan_params
    params.require(:book_loan).permit(:due, :returned, :person_id, :book_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:name, :isbn)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def login_form

    end

    def logout
        session.delete(:current_user_id)
        redirect_to :root
    end

    def login
        person = Person.find_by(name: params[:person][:name])
        if person
            session[:current_user_id] = person.id
            redirect_to :root
        else
            redirect_to :login_path
        end
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.require(:person).permit(:name, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_loans_helper.rb
module BookLoansHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/book_loans/_form.html.erb
<%= form_with(model: book_loan, local: true) do |form| %>
  <% if book_loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_loan.errors.count, "error") %> prohibited this book_loan from being saved:</h2>

      <ul>
        <% book_loan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :due %>
    <%= form.datetime_select :due %>
  </div>

  <div class="field">
    <%= form.label :returned %>
    <%= form.check_box :returned %>
  </div>

  <div class="field">
    <%= form.label :person_id %>
    <%= form.number_field :person_id %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.number_field :book_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_loans/edit.html.erb
<h1>Editing Book Loan</h1>

<%= render "form", book_loan: @book_loan %>

<%= link_to "Show", @book_loan %> |
<%= link_to "Back", book_loans_path %>

app/views/book_loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= BookLoan.count %> Book Loans</h1>

<table>
  <thead>
    <tr>
      <th>Due</th>
      <th>Returned</th>
      <th>Person</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_loans.each do |book_loan| %>
      <tr>
        <td><%= book_loan.due %></td>
        <td><%= book_loan.returned %></td>
        <td><%= book_loan.person.name %></td>
        <td><%= book_loan.book.name %></td>
        <td><%= link_to "Show", book_loan %></td>
        <td><%= link_to "Edit", edit_book_loan_path(book_loan) %></td>
        <td><%= link_to "Destroy", book_loan, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Book Loan", new_book_loan_path %>

app/views/book_loans/new.html.erb
<h1>New Book Loan</h1>

<%= render "form", book_loan: @book_loan %>

<%= link_to "Back", book_loans_path %>

app/views/book_loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Due:</strong>
  <%= @book_loan.due %>
</p>

<p>
  <strong>Status</strong>
  <% if @book_loan.returned %>
    Returned
  <% else %>
    On Loan
  <% end %>
</p>

<p>
  <strong>Person:</strong>
  <%= @book_loan.person.name %>
</p>

<p>
  <strong>Book:</strong>
  <%= @book_loan.book.name %>
</p>

<%= link_to "Edit", edit_book_loan_path(@book_loan) %> |
<%= link_to "Back", book_loans_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render "form", book: @book %>

<%= link_to "Show", @book %> |
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Isbn</th>
      <th>Status</th>
      <th>Borrow</th>
      <th>Return</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.isbn %></td>
        <td>
          <% if book.book_loans.count == 0 %>
         Available 
         <% else %>
          <%= link_to "On Loan", book_loan_path(book.book_loans.first) %>
        <% end %>
        </td>
        <td>
          <% if book.book_loans.count == 0 %>
            <%= form_for :book, url: loan_book_path, method: :post do |f| %>
              <%= f.hidden_field :book_id, value: book.id %>
              <%= f.submit(:read.capitalize, {:class => 'btn btn-info'}) %>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if book.book_loans.first && book.book_loans.first.person_id == session[:current_user_id] %>
            <%= form_for :book_loan, url: return_book_path, method: :patch do |f| %>
              <%= f.hidden_field :book_loan_id, value: book.book_loans.first.id %>
              <%= f.submit(:return.capitalize, {:class => 'btn btn-info'}) %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to "Show", book %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Destroy", book, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Book", new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render "form", book: @book %>

<%= link_to "Back", books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<%= link_to "Edit", edit_book_path(@book) %> |
<%= link_to "Back", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <div class="container" style="padding: 0 10% 0 10%">
      <div class="nav" style="display: flex; flex-direction: row; justify-content: space-between; width: 100%">
        <div class="nav-links" style="display: flex; flex-direction: row; justify-content: space-around; width: 300px">
          <div>
              <%= link_to "Books", books_path, :class => "nav-link" %>
          </div>
          <div>
              <%= link_to "People", people_path, :class => "nav-link" %>
          </div>
          <div>
              <%= link_to "Loans", book_loans_path, :class => "nav-link" %>
          </div>
        </div>
        <div>
          <% if session[:current_user_id] %>
            <%= Person.find_by(id: session[:current_user_id]).name %>
            <%= link_to "Logout", logout_path, :class => "nav-link" %>
          <% else %>
            <%= link_to "Login", login_path, :class => "nav-link" %>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/login/login_form.html.erb
<%= form_for :person, url: login_path, method: :post do |f| %>
    <% if @errors %>
        <% @errors.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :name %>
        <%= f.text_field(:name, { :class => "form-control" }) %>
    </p>
    <p>
        <%= f.submit(:login.capitalize, { :class => "btn btn-info" }) %>
    </p>
<% end %>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render "form", person: @person %>

<%= link_to "Show", @person %> |
<%= link_to "Back", people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.role %></td>
        <td><%= link_to "Show", person %></td>
        <td><%= link_to "Edit", edit_person_path(person) %></td>
        <td><%= link_to "Destroy", person, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Person", new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render "form", person: @person %>

<%= link_to "Back", people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @person.role %>
</p>

<%= link_to "Edit", edit_person_path(@person) %> |
<%= link_to "Back", people_path %>